spring:
  application:
    name: api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: aghaprigqprjgnqpjrgnqpgjnqpgjnqlrkgjnqrgkjnqrkgjnqe